apiVersion: apps/v1
kind: Deployment
metadata:
  name: ag
  namespace: test-abdullah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ag
  template:
    metadata:
      labels:
        app: ag
    spec:
      containers:
      - name: ag
        image: abdullahalmariah/auction-gateway:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "redis-cluster"
        - name: REDIS_APPLOVIN_HOST
          value: "redis-cluster"
        - name: REDIS_QPS_HOST
          value: "redis-cluster"
        - name: REDIS_CRITEO_HOST
          value: "redis-cluster"
        - name: APPLICATION_SECRET
          value: "APPLICATION_SECRET"
        - name: EU_ENDPOINTS
          value: "localhost"
        - name: US_ENDPOINTS
          value: "localhost"
        - name: KAFKA_BROKERS
          value: "kafka-0:29092,kafka-1:29092,kafka-2:29092"
        - name: KAFKA_BID_REQUESTS_TOPIC
          value: bid_requests
        - name: KAFKA_BIDS_TOPIC
          value: bids
        - name: KAFKA_ADNETWORK_BIDS_TOPIC
          value: adnetwork_bids
        - name: KAFKA_ADNETWORK_REQUEST_TOPIC
          value: adnetwork_request
        - name: KAFKA_DEBUG_BID_REQUEST_TOPIC
          value: debug_bid_request
        - name: LAGOM_LOCATOR_NAME
          value: "k8s"
        - name: NAMESPACE
          value: "test-abdullah"
        - name: MARKETPLACES_BY_SELLER
          value: "test1:open"
        - name: ADNETWORK_PUBMATIC_RTB_PUBLISHER_ID
          value: "test1"
        - name: ADNETWORK_PUBMATIC_RTB_ENABLED_APPS
          value: "test"
        - name: ADNETWORK_PUBMATIC_PB_PUBLISHER_ID
          value: "test1"
        - name: ADNETWORK_PUBMATIC_PB_ENABLED_APPS
          value: "test"       
        - name: ADNETWORK_RUBICON_BANNER_ZONE_300_250
          value: "12"
        - name: ADNETWORK_RUBICON_BANNER_ZONE_320_50
          value: "12"
        - name: ADNETWORK_RUBICON_BANNER_ZONE_320_480
          value: "12"
        - name: ADNETWORK_RUBICON_BANNER_ZONE_480_320
          value: "12"
        - name: ADNETWORK_RUBICON_BANNER_ZONE_728_90
          value: "12"
        - name: ADNETWORK_RUBICON_BANNER_ZONE_768_1024
          value: "12"
        - name: ADNETWORK_RUBICON_BANNER_ZONE_1024_768
          value: "22"
        - name: ADNETWORK_CRITEO_ZONE_320_50
          value: "22"
        - name: ADNETWORK_CRITEO_ZONE_728_90
          value: "22"
        - name: ADNETWORK_CRITEO_ZONE_320_480
          value: "22"
        - name: ADNETWORK_CRITEO_ZONE_480_320
          value: "22"
        - name: ADNETWORK_CRITEO_ZONE_768_1024
          value: "22"
        - name: ADNETWORK_CRITEO_ZONE_1024_768
          value: "22"
        - name: ADNETWORK_CRITEO_RU_ZONE_320_50
          value: "22"
        - name: ADNETWORK_CRITEO_RU_ZONE_480_320
          value: "22"
        - name: ADNETWORK_CRITEO_RU_ZONE_320_480
          value: "22"
        - name: ADNETWORK_CRITEO_RU_ZONE_1024_768
          value: "22"
        - name: ADNETWORK_CRITEO_RU_ZONE_768_1024
          value: "22"
        - name: ADNETWORK_CRITEO_RU_ZONE_728_90
          value: "22"
        - name: ADNETWORK_CRITEO_US_ZONE_320_50
          value: "22"
        - name: ADNETWORK_CRITEO_US_ZONE_728_90
          value: "22"
        - name: ADNETWORK_CRITEO_US_ZONE_320_480
          value: "22"
        - name: ADNETWORK_CRITEO_US_ZONE_480_320
          value: "22"
        - name: ADNETWORK_CRITEO_US_ZONE_768_1024
          value: "22"
        - name: ADNETWORK_CRITEO_US_ZONE_1024_768
          value: "22"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss
  namespace: test-abdullah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ss
  template:
    metadata:
      labels:
        app: ss
    spec:
      containers:
      - name: ss
        image: abdullahalmariah/settings-service:latest
        imagePullPolicy: Always
        env:
        - name: APPLICATION_SECRET
          value: "APPLICATION_SECRET"
        - name: LAGOM_LOCATOR_NAME
          value: "k8s"
        - name: NAMESPACE
          value: "test-abdullah"
        - name: DATABASE_URL_BUYER
          value: "jdbc:postgresql://postgres/buyer?user=postgres&password=yTXP12OMTXM07LCs"
        - name: DATABASE_URL_SELLER
          value: "jdbc:postgresql://postgres/seller?user=postgres&password=yTXP12OMTXM07LCs"
        - name: EXTERNAL_DOMAIN
          value: "example.com"
        - name: EXTERNAL_USER
          value: "user"
        - name: EXTERNAL_PASS
          value: "pass"
        - name: ENV
          value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: test-abdullah
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: test-abdullah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: abdullahalmariah/api-gateway:latest
        imagePullPolicy: Always
        env:
        - name: APPLICATION_SECRET
          value: "APPLICATION_SECRET"
        - name: LAGOM_LOCATOR_NAME
          value: "k8s"
        - name: NAMESPACE
          value: "test-abdullah"
        - name: DATABASE_URL
          value: "jdbc:postgresql://postgres/default?user=postgres&password=yTXP12OMTXM07LCs"
        - name: ENV
          value: prod